import Vue from 'vue'
import { wrapFunctional } from './utils'

const components = {
  AlertComponent: () => import('../..\\components\\AlertComponent.vue' /* webpackChunkName: "components/alert-component" */).then(c => wrapFunctional(c.default || c)),
  Consulting: () => import('../..\\components\\Consulting.vue' /* webpackChunkName: "components/consulting" */).then(c => wrapFunctional(c.default || c)),
  Cookie: () => import('../..\\components\\Cookie.vue' /* webpackChunkName: "components/cookie" */).then(c => wrapFunctional(c.default || c)),
  CounterMarginLess: () => import('../..\\components\\CounterMarginLess.vue' /* webpackChunkName: "components/counter-margin-less" */).then(c => wrapFunctional(c.default || c)),
  CounterSection: () => import('../..\\components\\CounterSection.vue' /* webpackChunkName: "components/counter-section" */).then(c => wrapFunctional(c.default || c)),
  CounterUpcoming: () => import('../..\\components\\CounterUpcoming.vue' /* webpackChunkName: "components/counter-upcoming" */).then(c => wrapFunctional(c.default || c)),
  Demo: () => import('../..\\components\\Demo.vue' /* webpackChunkName: "components/demo" */).then(c => wrapFunctional(c.default || c)),
  DigitalDocumentation: () => import('../..\\components\\DigitalDocumentation.vue' /* webpackChunkName: "components/digital-documentation" */).then(c => wrapFunctional(c.default || c)),
  Documentry: () => import('../..\\components\\Documentry.vue' /* webpackChunkName: "components/documentry" */).then(c => wrapFunctional(c.default || c)),
  EfsLogin: () => import('../..\\components\\EfsLogin.vue' /* webpackChunkName: "components/efs-login" */).then(c => wrapFunctional(c.default || c)),
  EfsPledgeRegister: () => import('../..\\components\\EfsPledgeRegister.vue' /* webpackChunkName: "components/efs-pledge-register" */).then(c => wrapFunctional(c.default || c)),
  EmbedTranslate: () => import('../..\\components\\EmbedTranslate.vue' /* webpackChunkName: "components/embed-translate" */).then(c => wrapFunctional(c.default || c)),
  EmbedTwitter: () => import('../..\\components\\EmbedTwitter.vue' /* webpackChunkName: "components/embed-twitter" */).then(c => wrapFunctional(c.default || c)),
  EsfMembers: () => import('../..\\components\\EsfMembers.vue' /* webpackChunkName: "components/esf-members" */).then(c => wrapFunctional(c.default || c)),
  Esg: () => import('../..\\components\\Esg.vue' /* webpackChunkName: "components/esg" */).then(c => wrapFunctional(c.default || c)),
  EventTimeline: () => import('../..\\components\\EventTimeline.vue' /* webpackChunkName: "components/event-timeline" */).then(c => wrapFunctional(c.default || c)),
  GetCertificate: () => import('../..\\components\\GetCertificate.vue' /* webpackChunkName: "components/get-certificate" */).then(c => wrapFunctional(c.default || c)),
  GetVerify: () => import('../..\\components\\GetVerify.vue' /* webpackChunkName: "components/get-verify" */).then(c => wrapFunctional(c.default || c)),
  GuestCard: () => import('../..\\components\\GuestCard.vue' /* webpackChunkName: "components/guest-card" */).then(c => wrapFunctional(c.default || c)),
  IntellectualSupport: () => import('../..\\components\\IntellectualSupport.vue' /* webpackChunkName: "components/intellectual-support" */).then(c => wrapFunctional(c.default || c)),
  InternshipForm: () => import('../..\\components\\InternshipForm.vue' /* webpackChunkName: "components/internship-form" */).then(c => wrapFunctional(c.default || c)),
  LetterSlider: () => import('../..\\components\\LetterSlider.vue' /* webpackChunkName: "components/letter-slider" */).then(c => wrapFunctional(c.default || c)),
  Logo: () => import('../..\\components\\Logo.vue' /* webpackChunkName: "components/logo" */).then(c => wrapFunctional(c.default || c)),
  MasterAboutUs: () => import('../..\\components\\MasterAboutUs.vue' /* webpackChunkName: "components/master-about-us" */).then(c => wrapFunctional(c.default || c)),
  MasterFooter: () => import('../..\\components\\MasterFooter.vue' /* webpackChunkName: "components/master-footer" */).then(c => wrapFunctional(c.default || c)),
  MasterFooterTwo: () => import('../..\\components\\MasterFooterTwo.vue' /* webpackChunkName: "components/master-footer-two" */).then(c => wrapFunctional(c.default || c)),
  MasterGallery: () => import('../..\\components\\MasterGallery.vue' /* webpackChunkName: "components/master-gallery" */).then(c => wrapFunctional(c.default || c)),
  MasterSlider: () => import('../..\\components\\MasterSlider.vue' /* webpackChunkName: "components/master-slider" */).then(c => wrapFunctional(c.default || c)),
  MediaAdvocacy: () => import('../..\\components\\MediaAdvocacy.vue' /* webpackChunkName: "components/media-advocacy" */).then(c => wrapFunctional(c.default || c)),
  MemberCard: () => import('../..\\components\\MemberCard.vue' /* webpackChunkName: "components/member-card" */).then(c => wrapFunctional(c.default || c)),
  MemberDialog: () => import('../..\\components\\MemberDialog.vue' /* webpackChunkName: "components/member-dialog" */).then(c => wrapFunctional(c.default || c)),
  NestedMenu: () => import('../..\\components\\NestedMenu.vue' /* webpackChunkName: "components/nested-menu" */).then(c => wrapFunctional(c.default || c)),
  NumberCounter: () => import('../..\\components\\NumberCounter.vue' /* webpackChunkName: "components/number-counter" */).then(c => wrapFunctional(c.default || c)),
  PledgeCert: () => import('../..\\components\\PledgeCert.vue' /* webpackChunkName: "components/pledge-cert" */).then(c => wrapFunctional(c.default || c)),
  PledgeDetail: () => import('../..\\components\\PledgeDetail.vue' /* webpackChunkName: "components/pledge-detail" */).then(c => wrapFunctional(c.default || c)),
  PledgeList: () => import('../..\\components\\PledgeList.vue' /* webpackChunkName: "components/pledge-list" */).then(c => wrapFunctional(c.default || c)),
  PledgeRegister: () => import('../..\\components\\PledgeRegister.vue' /* webpackChunkName: "components/pledge-register" */).then(c => wrapFunctional(c.default || c)),
  PledgeVerify: () => import('../..\\components\\PledgeVerify.vue' /* webpackChunkName: "components/pledge-verify" */).then(c => wrapFunctional(c.default || c)),
  PrimaryAppBar: () => import('../..\\components\\PrimaryAppBar.vue' /* webpackChunkName: "components/primary-app-bar" */).then(c => wrapFunctional(c.default || c)),
  Research: () => import('../..\\components\\Research.vue' /* webpackChunkName: "components/research" */).then(c => wrapFunctional(c.default || c)),
  SecondMaster: () => import('../..\\components\\SecondMaster.vue' /* webpackChunkName: "components/second-master" */).then(c => wrapFunctional(c.default || c)),
  ShowSnack: () => import('../..\\components\\ShowSnack.vue' /* webpackChunkName: "components/show-snack" */).then(c => wrapFunctional(c.default || c)),
  SimpleMaster: () => import('../..\\components\\SimpleMaster.vue' /* webpackChunkName: "components/simple-master" */).then(c => wrapFunctional(c.default || c)),
  SocialSection: () => import('../..\\components\\SocialSection.vue' /* webpackChunkName: "components/social-section" */).then(c => wrapFunctional(c.default || c)),
  SrcEventCountdown: () => import('../..\\components\\SrcEventCountdown.vue' /* webpackChunkName: "components/src-event-countdown" */).then(c => wrapFunctional(c.default || c)),
  SrcLoader: () => import('../..\\components\\SrcLoader.vue' /* webpackChunkName: "components/src-loader" */).then(c => wrapFunctional(c.default || c)),
  StartupDialog: () => import('../..\\components\\StartupDialog.vue' /* webpackChunkName: "components/startup-dialog" */).then(c => wrapFunctional(c.default || c)),
  TakePledge: () => import('../..\\components\\TakePledge.vue' /* webpackChunkName: "components/take-pledge" */).then(c => wrapFunctional(c.default || c)),
  TeamCard: () => import('../..\\components\\TeamCard.vue' /* webpackChunkName: "components/team-card" */).then(c => wrapFunctional(c.default || c)),
  TwitterCard: () => import('../..\\components\\TwitterCard.vue' /* webpackChunkName: "components/twitter-card" */).then(c => wrapFunctional(c.default || c)),
  TwitterGallery: () => import('../..\\components\\TwitterGallery.vue' /* webpackChunkName: "components/twitter-gallery" */).then(c => wrapFunctional(c.default || c)),
  UpcomingEvents: () => import('../..\\components\\UpcomingEvents.vue' /* webpackChunkName: "components/upcoming-events" */).then(c => wrapFunctional(c.default || c)),
  VoluntaryForm: () => import('../..\\components\\VoluntaryForm.vue' /* webpackChunkName: "components/voluntary-form" */).then(c => wrapFunctional(c.default || c)),
  VuetifyLogo: () => import('../..\\components\\VuetifyLogo.vue' /* webpackChunkName: "components/vuetify-logo" */).then(c => wrapFunctional(c.default || c))
}

for (const name in components) {
  Vue.component(name, components[name])
  Vue.component('Lazy' + name, components[name])
}
